jasper.rcpt.directory=C:\\RMS-Receipts\\
jasper.reports.directory=C:\\RMS-Reports\\
#inet.adapter.name=wlan1
inet.adapter.name=ens192
#inet.adapter.name=eth0
 
# # Enable SQL logging (optional)
# spring.jpa.show-sql=true
 
ssm4u.authgen.username=RMS
ssm4u.authgen.password=96692757
ssm4u.authgen.default.custRefNo=XS1423456
ssm4u.authgen.get.user.profile.url=http://integrasidev.ssm.com.my/ssm4uServiceRest/getUserProfile/1
ssm4u.authgen.notify.user.url=http://integrasidev.ssm.com.my/ssm4uServiceRest/notifyUser/1

angular.home-page.online-portal=https://localhost:4200/
 
using.spring.schedulerFactory=false
spring.quartz.job-store-type=jdbc
# Always create the Quartz database on startup
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.schema=classpath:tables_informix.sql
 
 
# Use Informix JDBC driver
spring.datasource.driverClassName=com.informix.jdbc.IfxDriver
#spring.datasource.jndi-name=ssm_jndi
 
# Set your Informix username and password
spring.datasource.username=informix
spring.datasource.password=SeizeTheDay!
spring.datasource.url=jdbc:informix-sqli://20.239.131.227:9090/ssm_rms3:INFORMIXSERVER=ol_informix1410
 
 
spring.main.allow-bean-definition-overriding=true
 
# Hibernate properties (if using Hibernate)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.InformixDialect
 
# Enable transaction management
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
 
# Enable Spring Boot's automatic configuration for JPA repositories
spring.data.jpa.repositories.bootstrap-mode=default
 
# Enable SQL logging (optional)
spring.jpa.show-sql=false
 
 
#Ensure AOP Proxies are Created:
spring.aop.proxy-target-class=true
 
#HikariCP configuration
#spring.datasource.hikari.maximumPoolSize=1
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.connection-timeout=60000
 
 
 
#RMS properties
#rms.application.allowOrigin =https://52.163.62.7:1443/mockcrs,http://52.163.62.7:1443/mockcrs,https://52.163.62.7:1443/rmsbo,http://52.163.62.7:1443/rmsbo,https://52.163.62.7:1443/rmsrest,http://52.163.62.7:1443/rmsrest,https://52.163.62.7:1443/rms,http://52.163.62.7:1443/rms,https://52.163.62.7:1443,http://52.163.62.7:1443,https://login.microsoftonline.com,http://localhost:4200,http://localhost:4300,https://localhost:4300,http://localhost:8080,http://127.0.0.1:4300,https://localhost:4200,https://localhost:8080,https://localhost:8443,https://localhost:9443,https://idprodev.ssm.com.my:8443,https://10.200.57.121:8080,https://ssm-dev.southeastasia.cloudapp.azure.com:2443,https://ssm-dev.southeastasia.cloudapp.azure.com:2444,https://ssm-dev.southeastasia.cloudapp.azure.com:2445,https://ssm-dev.southeastasia.cloudapp.azure.com:2446,http://ssm-dev-internal.internal.cloudapp.net:8080,https://ssm-dev-internal.internal.cloudapp.net:8080,https://ssm-dev.southeastasia.cloudapp.azure.com:2443,https://ssm-dev.southeastasia.cloudapp.azure.com:2443,https://ssm-dev.southeastasia.cloudapp.azure.com:2443,https://20.212.222.6:8080,https://20.212.222.6:2443,https://20.212.222.6:2443,https://pay.e-ghl.com
#rms.application.allowOrigin = #https://apps.ssm4u.com.my,https://idprodev.ssm.com.my:8443,https://pay.e-ghl.com,http://integrasidev.ssm.com.my,http://175.139.230.149:8585
 
# rms.application.allowOrigin = https://login.microsoftonline.com,http://localhost:4200,http://localhost:4300,https://localhost:4300,http://localhost:8080,http://127.0.0.1:4300,https://localhost:4200,https://localhost:8080,https://localhost:8443,https://localhost:9443,https://idprodev.ssm.com.my:8443,https://10.200.57.121:8080,https://ssm-dev.southeastasia.cloudapp.azure.com:2443,https://ssm-dev.southeastasia.cloudapp.azure.com:2444,https://ssm-dev.southeastasia.cloudapp.azure.com:2445,https://ssm-dev.southeastasia.cloudapp.azure.com:2446,http://ssm-dev-internal.internal.cloudapp.net:8080,https://ssm-dev-internal.internal.cloudapp.net:8080,https://ssm-dev.southeastasia.cloudapp.azure.com:2443,https://ssm-dev.southeastasia.cloudapp.azure.com:2443,https://ssm-dev.southeastasia.cloudapp.azure.com:2443,https://20.212.222.6:8080,https://20.212.222.6:2443,https://20.212.222.6:2443,https://pay.e-ghl.com
rms.application.allowOrigin = classpath:allow-origin.txt
#change according to the environment
# below for local dev
rms.application.GHLServiceID = sit
rms.application.GHLPw = sit12345
rms.application.callBackURL= https://localhost:8080/api/onlinepayment/v1/backend
rms.application.SAMLSecurityConfigPort = 8080
rms.application.onlinePortalURL=https://localhost:4200/
server.servlet.session.cookie.name = RMS_JSESSIONID
rms.application.backPortalURL=https://localhost:4300/
rms.application.auditlogEnable = true
rms.application.sendEmailEnable = false
rms.application.emailTo = roy.low@mtechnologies.com.my
rms.application.emailCC = roy.low@mtechnologies.com.my,lor.cl@mtechnologies.com.my
#log level >>> ALL, WARNING, ERROR, DEBUG, INFO
rms.application.LogLevel = ALL
rms.application.WriteToFileEnable = false
rms.application.WriteFilePath = C:/Temp/RMS
rms.application.WriteFileMaxFileSizeInMB = 10
rms.application.WriteFileMaxFileRolling = 5

 
#default time zone
spring.jackson.time-zone=UTC
 
# Pretty print SQL queries
spring.jpa.properties.hibernate.format_sql=true
 
# Log JDBC parameters
logging.level.org.hibernate.type.descriptor.sql=info
# Log the SQL statements
logging.level.org.hibernate.SQL=info
 
logging.level.org.springframework = INFO
logging.level.org.springframework.jdbc.core = INFO
logging.level.org.springframework.web.cors=INFO
logging.level.org.springframework.security.web.FilterChainProxy=INFO
logging.level.org.springframework.beans.factory = DEBUG
 
# change according to the environment
# local dev
server.port=8314
server.ssl.enabled=false
server.ssl.key-store=classpath:SSL/keystore.jks
server.ssl.key-store-password=password
server.ssl.key-password=password

#debugging
server.error.include-message=always

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.db.enabled=true
management.health.diskspace.enabled=true
management.endpoint.health.groups.endpoints.include=arrEndpoint