package com.maven.rms.utils;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum ControllersEnum {
    AUDIT_LOG_CONTROLLER("100C"),
    AUTH_CONTROLLER("110C"),
    BANK_RECON_CONTROLLER("120C"),
    BANK_RECON_DETAIL_CONTROLLER("130C"),
    BANK_RECON_SCH_CONTROLLER("140C"),
    COMMON_CONTROLLER("150C"),
    DEFERRED_INCOME_CONTROLLER("160C"),
    FEE_GROUP_CONTROLLER("170C"),
    FMS_ACCOUNT_CONTROLLER("180C"),
    FMS_CONTROLLER("190C"),
    FMS_LEDGER_CONTROLLER("200C"),
    FMS_LEDGER_DOC_CONTROLLER("210C"),
    FPASCHEDULER_CONTROLLER("220C"),
    LOGIN_CONTROLLER("230C"),
    MFT_CONTROLLER("240C"),
    MFT_EMAIL_CONTROLLER("250C"),
    MFT_WF_CONTROLLER("260C"),
    MFT_WF_DOC_CONTROLLER("270C"),
    MFT_WF_HISTORY_CONTROLLER("280C"),
    MTT_CONTROLLER("290C"),
    MTT_LISTING_CONTROLLER("300C"),
    ONLINE_PAYMENT_CONTROLLER("310C"),
    PG_RECON_CONTROLLER("320C"),
    PG_RECON_SCH_CONTROLLER("330C"),
    RECON_REPORT_AND_ACCOUNT("340C"),
    REPORT_CONTROLLER("350C"),
    REPORT_UTL_CONTROLLER("360C"),
    RICP_CONTROLLER("370C"),
    RIPL_CONTROLLER("380C"),
    ROLE_AND_PERMISSIONS_CONFIGURATION_CONTROLLER("390C"),
    SCHEDULER_CONTROLLER("400C"),
    TAX_CODE_CONTROLLER("410C"),
    UAM_CONTROLLER("420C"),
    UNMATCH_TRANS_DAY_CONTROLLER("430C"),
    UNMATCH_TRANS_MONTH_CONTROLLER("440C"),
    USER_ROLE_CONTROLLER("450C"),
    DASHBOARD_CONTROLLER("460C"),

    REFUND_ACCOUNT_CODE_CONTROLLER("470C"),
    BRANCH_CODE_COUNTER_CONTROLLER("480C"),
    HELPER_CONTROLLER("490C"),
    OTC_RECEIPT_CANCELLATION_CONTROLLER("500C"),
    BILLING_ISSUANCE_BY_SS_CONTROLLER("510C"),
    OTC_EMV_RECONCILIATION_CONTROLLER("520C"),
    RILT_CONTROLLER("530C"),
    REFUNDPTT_LISTING_CONTROLLER("540C"),
    REFUND_CONTROLLER("550C"),
    BILLING_CONTRILLER("560C"),
    MYTASKS_PUBLICTASKS_CONTROLLER("570C"),
    OTC_COUNTER_BALANCING_CONTROLLER("580C"),
    
    OTC_COLLECTION_RECEIPTING_CONTROLLER("590C"),
    OTC_RETURNED_CHEQUE_CONTROLLER("600C"),
    NON_RMS_RECEIPTING_CONTROLLER("610C"),
    CREDIT_CONTROL_SME_TASK_LIST_CONTROLLER("620C");


    private final String value;
}
